### PR TITLE
Fixes scripts for Linux agent

### LINKED ISSUE #23: Agent creation fails for Linux machines
The preparation for Linux VM is flawed.

While in the prepare script JDK 13 gets downloaded and installed in the start script references a JDK 12 installation.

__Prepare script__

https://github.com/gocd/azure-elastic-agent-plugin/blob/73374433c593102f52eb9cf4dc36bbb0f4a8cb14/src/main/resources/post_provision_script.template.ftlh#L5
https://github.com/gocd/azure-elastic-agent-plugin/blob/73374433c593102f52eb9cf4dc36bbb0f4a8cb14/src/main/resources/post_provision_script.template.ftlh#L15

__Start script__

https://github.com/gocd/azure-elastic-agent-plugin/blob/73374433c593102f52eb9cf4dc36bbb0f4a8cb14/src/main/resources/linux_start_go_agent.template.flth#L4

### PR DESCRIPTION
**Pull request by joestr**
**Changes**:
- Download and install latest JDK 11
- Start agent with installed JDK 11
- Fixes #23

### CODE REVIEW

**Comment by chadlwilson** [comment]
Generally speaking, GoCD packages and endorses only the Adoptium / Temurin JDKs. That's what we re-package with the docker images, Windows+Mac installers, Linux distros etc. There were a few peripheral places like this using the "official" OpenJDK builds. One can directly link to the relevant binary from say https://github.com/adoptium/temurin17-binaries/releases/tag/jdk-17.0.5%2B8

Need to think about this a little bit, but my gut feel is we are better to package JDK 17. That is the version that we package as a default everywhere else, and full regression currently only runs against JDK 17.

There's a bit of a challenge here insofar as
- JDK17 will only work fine with GoCD Server `>= 22.1.0` 
- JDK11 will only work fine with GoCD Server `< 21.2.0` or `>= 22.1.0` (for some reason source compatibility was increased to JDK 13 changed in `21.2.0`. We [reverted this](https://github.com/gocd/gocd/pull/10153) back to an LTS version in `22.1.0`)

So there is no LTS JDK version that will work correctly with GoCD 21.2.0 or 21.3.0. That's OK, it's only two versions. For folks running older versions, I think it's fair that they will need to install their own/build their own image etc.

Which GoCD version are you folk using, I wonder?

**Comment by chadlwilson** [comment]
FWIW, there is some similar (more complex as handles multi-arch) dodgy shell scripting in https://github.com/gocd-contrib/gocd-trial-launcher/blob/9721a6b052f82b81559d7bc0a9617707499b823a/assembly/package.sh#L215-L276 that downloads temurin JREs for the purpose of the GoCD test drive at https://www.gocd.org/test-drive-gocd.html

**Comment by joestr** [comment]
I can only speak for myself, my GoCD Server runs on JDK 11 and the agent is also happy with it.

I see no issue using Adoptium JRE 17 during installation making it architecture agnostic would be really great too, but that's for another issue ticket.

**Comment by joestr** [comment]
Uses Adoptiums JDK 17 JRE now

**Comment by chadlwilson** [comment]
Thanks! Made a few tweaks in #27.

Are you able to give https://github.com/gocd/azure-elastic-agent-plugin/releases/tag/v1.2.0-53-exp a go and let me know how it goes?

Will only work on GoCD `21.4.0`+ (which has the required Java 17 compatibility without various hacks).

**Pull request merged**
